var express = require('express');
var router = express.Router();

router.get('/', function(req, res, next) {
    res.header('Content-Type', 'text/xml');
    res.send(`<?xml version="1.0" encoding="UTF-8"?>
        <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <url>
                <loc>https://utarid.org/sitemap</loc>
                <lastmod>2025-07-16T00:00:00+00:00</lastmod>
                <changefreq>yearly</changefreq>
                <priority>1.0</priority>
            </url>
            <url>
                <loc>https://utarid.org/single/spring-cloud-gateway-ile-load-balancing</loc>
                <lastmod>2025-07-16T00:00:00+00:00</lastmod>
                <changefreq>yearly</changefreq>
                <priority>1.0</priority>
            </url>
            <url>
                <loc>https://utarid.org/single/spring-boot-config-server</loc>
                <lastmod>2025-07-11T00:00:00+00:00</lastmod>
                <changefreq>yearly</changefreq>
                <priority>1.0</priority>
            </url>
            <url>
                <loc>https://utarid.org/single/spring-boot-ta-zipkin-kullanimi</loc>
                <lastmod>2025-05-22T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/spring-boot-ta-openfeign-kullanimi</loc>
                <lastmod>2025-05-05T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/bom</loc>
                <lastmod>2025-04-06T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/spring-boot-actuator</loc>
                <lastmod>2025-02-15T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/questdb</loc>
                <lastmod>2025-01-25T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/cors</loc>
                <lastmod>2025-01-22T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/bill-pugh-singleton-design</loc>
                <lastmod>2025-01-18T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/java-reflection</loc>
                <lastmod>2025-01-12T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/singleton-nesnelerde-readResolve-kullanimi</loc>
                <lastmod>2025-01-12T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/enum-sabiti-singleton-midir</loc>
                <lastmod>2025-01-11T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/double-checked-locking</loc>
                <lastmod>2025-01-06T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/method-interceptor</loc>
                <lastmod>2024-12-28T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/dependency-injection</loc>
                <lastmod>2024-12-14T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/checked-exception-ve-unchecked-exception</loc>
                <lastmod>2024-12-09T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/aot-ve-jit-kavramlari</loc>
                <lastmod>2024-10-12T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/linuxte-postgresql-kurulumu</loc>
                <lastmod>2024-02-22T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/thread</loc>
                <lastmod>2023-12-04T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/executor</loc>
                <lastmod>2023-12-04T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/executorservice</loc>
                <lastmod>2023-12-04T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/future</loc>
                <lastmod>2023-12-04T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/completablefuture</loc>
                <lastmod>2023-12-04T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/postgresql-veritabaninda-coalesce-kullanimi</loc>
                <lastmod>2023-11-29T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/encode()-ve-decode()</loc>
                <lastmod>2023-11-27T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/servlet-listenerlar</loc>
                <lastmod>2023-09-12T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/spring-boot-gateway</loc>
                <lastmod>2023-07-22T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/spring-boot-ta-eureka-kullanimi</loc>
                <lastmod>2025-04-13T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/linuxte-mongodb-kurulumu</loc>
                <lastmod>2023-07-07T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/open-closed-principle</loc>
                <lastmod>2023-06-11T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/oop-kavramlari:-aggregation</loc>
                <lastmod>2023-06-09T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/oop-kavramlari</loc>
                <lastmod>2023-06-09T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/oop-kavramlari:-composition</loc>
                <lastmod>2023-06-09T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/liskov-substitution-principle</loc>
                <lastmod>2023-06-09T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/auto-boxing</loc>
                <lastmod>2023-06-08T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/java-nio-api</loc>
                <lastmod>2023-06-08T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/java-io-api</loc>
                <lastmod>2023-06-08T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/referans-turleri</loc>
                <lastmod>2023-06-06T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/constructor-chaining</loc>
                <lastmod>2023-06-05T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/concurrency</loc>
                <lastmod>2023-06-04T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/busy-spin</loc>
                <lastmod>2023-06-04T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/spring-boot-restTemplate</loc>
                <lastmod>2023-05-27T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/spring-boot-ta-guvenlik</loc>
                <lastmod>2023-05-25T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/spring-boot-ta-veritabani-anotasyonlari</loc>
                <lastmod>2023-05-21T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/temel-spring-boot-uygulamasi</loc>
                <lastmod>2023-05-17T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/spring-boot-ta-validation-yapmak</loc>
                <lastmod>2023-05-10T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/linux-te-wifi-yapilandirmasi</loc>
                <lastmod>2023-05-08T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/mapstruct-kullanimi</loc>
                <lastmod>2023-05-07T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/spring-boot-ta-loglama-yapmak</loc>
                <lastmod>2023-05-02T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/exceptionHandler-kullanimi</loc>
                <lastmod>2023-05-01T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/lombok-kullanimi</loc>
                <lastmod>2023-04-29T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/primary-ve-qualifier-kullanimi</loc>
                <lastmod>2023-04-28T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/veri-yapilari:-linked-list</loc>
                <lastmod>2023-03-13T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/event-driven-programlama</loc>
                <lastmod>2023-03-05T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/comparator-ve-comparable</loc>
                <lastmod>2023-02-13T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/veri-yapilari:-map</loc>
                <lastmod>2023-02-11T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/veri-yapilari:-stack</loc>
                <lastmod>2023-02-06T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/veri-yapilari:-queue</loc>
                <lastmod>2023-02-05T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/veri-yapilari:-array</loc>
                <lastmod>2023-02-04T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/veri-yapilari:-set</loc>
                <lastmod>2023-02-02T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/try-with-resources</loc>
                <lastmod>2023-01-27T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/List.of-ve-Arrays.asList</loc>
                <lastmod>2023-01-27T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/iterator</loc>
                <lastmod>2023-01-26T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/design-patterns</loc>
                <lastmod>2023-01-21T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/oop-kavramlari:-inheritance</loc>
                <lastmod>2023-01-03T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/BigDecimal</loc>
                <lastmod>2022-12-29T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/optional</loc>
                <lastmod>2022-12-10T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/base64-encoding</loc>
                <lastmod>2022-12-06T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/generic-tipler</loc>
                <lastmod>2022-11-26T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/lambda-kullanimi</loc>
                <lastmod>2022-11-25T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/stream-api</loc>
                <lastmod>2022-11-23T00:00:00+00:00</lastmod>
            </url>
            <url>
                <loc>https://utarid.org/single/content-provider-kullanimi</loc>
                <lastmod>2021-07-26</lastmod>
                <changefreq>yearly</changefreq>
                <priority>1.0</priority>
            </url>
            <url>
                <loc>https://utarid.org/single/runtime-izinlerin-alinmasi</loc>
                <lastmod>2021-07-25</lastmod>
                <changefreq>yearly</changefreq>
                <priority>1.0</priority>
            </url>
        </urlset>
        `);
    });

module.exports = router;
